In [1]:
from transformers import pipeline
unmasker = pipeline('fill-mask', model='bert-base-uncased')
unmasker("Hello I'm a [MASK] model.")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'sequence': "hello i'm a fashion model.",
  'score': 0.10731068253517151,
  'token': 4827,
  'token_str': 'fashion'},
 {'sequence': "hello i'm a role model.",
  'score': 0.08774490654468536,
  'token': 2535,
  'token_str': 'role'},
 {'sequence': "hello i'm a new model.",
  'score': 0.053383808583021164,
  'token': 2047,
  'token_str': 'new'},
 {'sequence': "hello i'm a super model.",
  'score': 0.04667206108570099,
  'token': 3565,
  'token_str': 'super'},
 {'sequence': "hello i'm a fine model.",
  'score': 0.027095943689346313,
  'token': 2986,
  'token_str': 'fine'}]

In [2]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [3]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)
print(output)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[ 0.13849437,  0.15803367, -0.29711083, ..., -0.27054793,
         -0.28428832,  0.45782942],
        [ 0.53699464, -0.23290282,  0.17522904, ...,  0.5544219 ,
          0.49878597, -0.00256851],
        [ 0.3004159 , -0.3476064 ,  0.12071918, ..., -0.45553666,
          0.3289878 ,  0.87703526],
        ...,
        [ 0.38067174,  0.12021175,  0.8279428 , ..., -0.862485  ,
         -0.5952897 ,  0.04667845],
        [-0.02531218, -0.7178523 , -0.6955405 , ...,  0.07610174,
         -0.6666528 , -0.34006792],
        [ 0.7532148 ,  0.2388873 ,  0.07205677, ...,  0.24649811,
         -0.645818  , -0.3215673 ]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.9376686 , -0.50426245, -0.9798984 ,  0.90303475,  0.93293625,
        -0.24378785,  0.89260286,  0.22877775, -0.9531078 , -0.99999535,
        -0.8861834 ,  0.9905511 ,  0.985522  

In [4]:
from transformers import pipeline
unmasker = pipeline('fill-mask', model='bert-base-uncased')
unmasker("The man worked as a [MASK].")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'sequence': 'the man worked as a carpenter.',
  'score': 0.09747551381587982,
  'token': 10533,
  'token_str': 'carpenter'},
 {'sequence': 'the man worked as a waiter.',
  'score': 0.05238323658704758,
  'token': 15610,
  'token_str': 'waiter'},
 {'sequence': 'the man worked as a barber.',
  'score': 0.04962710291147232,
  'token': 13362,
  'token_str': 'barber'},
 {'sequence': 'the man worked as a mechanic.',
  'score': 0.03788599371910095,
  'token': 15893,
  'token_str': 'mechanic'},
 {'sequence': 'the man worked as a salesman.',
  'score': 0.03768093138933182,
  'token': 18968,
  'token_str': 'salesman'}]